# Generated by Django 5.0.14 on 2026-07-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='ERINAYOMI', max_length=200)),
                ('business_email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, help_text='Digits only, with country code, e.g. 2348012345678', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store/')),
                ('address', models.TextField(blank=True)),
                ('business_hours', models.CharField(blank=True, max_length=200)),
                ('facebook_link', models.URLField(blank=True)),
                ('instagram_link', models.URLField(blank=True)),
                ('tiktok_link', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Settings',
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
