# Generated by Django 5.0.14 on 2026-08-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_settings', '0002_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Flat delivery fee in Naira, charged when the order is below the free shipping threshold.', max_digits=10),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='free_shipping_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Orders at or above this amount ship free. Leave blank to always charge the delivery fee.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='privacy_policy',
            field=models.TextField(blank=True, help_text='Shown on the policies page.'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='return_policy',
            field=models.TextField(blank=True, help_text='Shown on the policies page.'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='shipping_policy',
            field=models.TextField(blank=True, help_text='Shown on the policies page.'),
        ),
    ]
