# Generated by Django 5.0.14 on 2026-07-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TailoringAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('service_type', models.CharField(choices=[('agbada', 'Agbada / Native Wear'), ('kaftan', 'Kaftan'), ('suit', 'Suit'), ('alteration', 'Alteration'), ('other', 'Other / Custom')], default='other', max_length=20)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time', models.CharField(blank=True, max_length=50)),
                ('measurements_notes', models.TextField(blank=True, help_text="Chest, shoulder, sleeve, waist, etc. or 'need help taking measurements'.")),
                ('reference_notes', models.TextField(blank=True, help_text='Style references, fabric preference, occasion.')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
