# Generated by Django 5.0.14 on 2026-08-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_tailoringappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailoringappointment',
            name='completion_date',
            field=models.DateField(blank=True, help_text='When the customer needs the finished piece by.', null=True),
        ),
        migrations.AddField(
            model_name='tailoringappointment',
            name='inspiration_image',
            field=models.ImageField(blank=True, help_text='Optional style reference photo uploaded by the customer.', null=True, upload_to='tailoring/inspiration/'),
        ),
        migrations.AddField(
            model_name='tailoringappointment',
            name='measurement_chest',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tailoringappointment',
            name='measurement_hip',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tailoringappointment',
            name='measurement_length',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tailoringappointment',
            name='measurement_shoulder',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tailoringappointment',
            name='measurement_sleeve',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tailoringappointment',
            name='measurement_waist',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='tailoringappointment',
            name='measurements_notes',
            field=models.TextField(blank=True, help_text="Additional notes, or 'need help taking measurements'."),
        ),
    ]
