# Generated by Django 5.0.14 on 2026-07-31 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='Requested/estimated delivery date.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(blank=True, help_text="e.g. 'Morning (9am - 12pm)' or a specific time.", max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='order_notes',
            field=models.TextField(blank=True, help_text='Special instructions from the customer.'),
        ),
    ]
